const httpServer = require('http-server')

const PORT = 8000
const TEST_URL = `http://localhost:${PORT}`
var server

module.exports = {
  before: function(browser) {
    // Start a local server to serve the TodoMVC app.
    server = httpServer.createServer({ root: `${__dirname}/testapp` })
    server.listen(PORT)
  },

  after: function(browser) {
    // Shutdown the http server.
    server.close()
    // Close down the browser session.
    browser.end()
  },

  beforeEach: function(browser) {
    browser.url(TEST_URL)
  },

  afterEach: function(browser) {
    // Clear local storage between test cases.
    browser.execute('window.localStorage.clear()')
  },

  'snapshots with autogenerated name': function(browser) {
    browser.percySnapshot()
  },

  'snapshots with provided name': function(browser) {
    browser.percySnapshot('snapshots with provided name')
  },

  'snapshots with provided name and widths': function(browser) {
    browser.percySnapshot('snapshots with provided name and widths', { widths: [768, 992, 1200] })
  },

  'snapshots with provided name and minHeight': function(browser) {
    browser.percySnapshot('snapshots with provided name and minHeight', { minHeight: 2000 })
  },

  'takes multiple snapshots in one test': function(browser) {
    browser
      .sendKeys('.new-todo', 'A thing to accomplish')
      .sendKeys('.new-todo', browser.Keys.ENTER)
      .percySnapshot('takes multiple snapshots - #1', { widths: [768, 992, 1200] })
      .click('input.toggle')
      .percySnapshot('takes multiple snapshots - #2', { widths: [768, 992, 1200] })
  },
}
